server:
  port: ${PORT:6110}

issuer-uri: ${KEYCLOAK_BASE_URL:http://localhost:6010}

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:dh_core}
    username: ${PG_USER:dh_core}
    password: ${PG_PASSWORD:dh_core}
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost

redis:
  client:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:1}
    password: ${REDIS_PASSWORD:}