server:
  port: ${PORT:6120}

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:dh_core}
    username: ${PG_USER:dh_core}
    password: ${PG_PASSWORD:dh_core}
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:6010/realms/master
